-- MySQL Script generated by MySQL Workbench
-- Sat Apr  1 13:52:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mitienda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mitienda` ;

-- -----------------------------------------------------
-- Schema mitienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mitienda` DEFAULT CHARACTER SET utf8 ;
USE `mitienda` ;

-- -----------------------------------------------------
-- Table `mitienda`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mitienda`.`usuarios` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo_postal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitienda`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mitienda`.`productos` (
  `idproducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `precio` DECIMAL(10,2) UNSIGNED NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `stock` INT NOT NULL DEFAULT 0,
  `create_date` DATE NOT NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitienda`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mitienda`.`pedidos` (
  `idpedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `iduser` INT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `total` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpedido`),
  UNIQUE INDEX `idpedido_UNIQUE` (`idpedido` ASC) ,
  INDEX `fk_pedidos_usuarios_idx` (`iduser` ASC) ,
  CONSTRAINT `fk_pedidos_usuarios`
    FOREIGN KEY (`iduser`)
    REFERENCES `mitienda`.`usuarios` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitienda`.`pedidos_has_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mitienda`.`pedidos_has_productos` (
  `idpedido` INT UNSIGNED NOT NULL,
  `idproducto` INT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `precio_unitario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpedido`, `idproducto`),
  INDEX `fk_pedidos_has_productos_productos1_idx` (`idproducto` ASC) ,
  INDEX `fk_pedidos_has_productos_pedidos1_idx` (`idpedido` ASC) ,
  CONSTRAINT `fk_pedidos_has_productos_pedidos1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `mitienda`.`pedidos` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_productos1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `mitienda`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
